/*
 * generated by Xtext 2.20.0
 */
package org.xtext.thphr16.ide


/**
 * Use this class to register ide components.
 */
class MathinterpreteerIdeModule extends AbstractMathinterpreteerIdeModule {
}
